DELIMITER //

DROP PROCEDURE IF EXISTS hello//

CREATE PROCEDURE hello()
BEGIN
  CASE 
    WHEN CURRENT_TIME() BETWEEN '06:00:00' AND '12:00:00' THEN
	  SELECT 'Доброе утро';
	WHEN CURRENT_TIME() BETWEEN '12:00:00' AND '18:00:00' THEN
	  SELECT 'Добрый день';
	WHEN CURRENT_TIME() BETWEEN '18:00:00' AND '00:00:00' THEN
	  SELECT 'Добрый вечер';
	ELSE
	  SELECT 'Доброй ночи';
  END CASE;
END //

CALL hello()//

DELIMITER;